name: today_weather
description: Flutter mobx tutorial weather forcasting

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  provider: ^4.3.3
  location: ^3.2.4
  intl: ^0.16.1
  dio: ^3.0.10
  flare_flutter: ^2.0.6
  get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  mobx_codegen: ^1.1.2
  flutter_native_splash: ^0.3.0
  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/flares/
